[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ImgGallery"
version = "0.9"
dependencies = []

[tool.setuptools.packages.find]
where = ["."]
